# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b35b35ce7a54fc5de144792d5f9bfd4f9221c621c434620dc8556529c90dcb1ac59bc7a46d003a384647c11cc5840756af3f4077357ff6377be857c22e1bc2a

test:
  secret_key_base: 1d7dd783b9cd9f3e8a6570c89a514cff9431e4eb2eeafc8f3e1569683ffa52632813a029a40eecfb7080a79013cc450633399c8c719b0c5d0e7e3bd34f9fc024

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
